pub mod agent;
pub mod agent_logging;
pub mod capabilities;
pub mod completion;
pub mod config;
pub mod cozo;
pub mod doctor;
pub mod drift;
pub mod events;
pub mod graph;
pub mod harvest;
pub mod heartbeat;
pub mod hub;
pub mod managed_block;
pub mod mcp;
pub mod pattern;
pub mod progress;
pub mod scanner;
pub mod setup;
pub mod skills;
pub mod team;
pub mod tui;
pub mod version;
pub mod watch;
pub mod wiki;

pub use config::{find_config, KnobyteConfig};
pub use progress::{format_bytes, IndexProgressBar};
pub use version::VERSION;
